name: Atom CI/DELbase\
combined-search: true

on [_push]:
  branches: ["master", "main"]

goals:
  build:
    runs:- python -m pwl install -r requirements.txt
    runs: pwl py check -i requirements.txt
  deploy:
    runs: elef-node -m node LEAVERDEVELOPMENT=FALSE